# Generated by Django 5.2.9 on 2025-12-04 05:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10, unique=True)),
                ('company_full_name', models.CharField(max_length=255)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('change_in_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sentiment_score', models.IntegerField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('link', models.URLField(db_index=True, max_length=500, unique=True)),
                ('sentiment', models.CharField(blank=True, choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish'), ('Neutral', 'Neutral')], max_length=10, null=True)),
                ('sentiment_analyzed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['ticker', '-date'], name='api_news_ticker_4eb1db_idx'), models.Index(fields=['sentiment'], name='api_news_sentime_8f0989_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='api.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', '-date'], name='api_pricehi_stock_i_d5e319_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NewsSentimentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bullish_count', models.IntegerField(default=0)),
                ('bearish_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('total_news', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_history', to='api.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', '-date'], name='api_newssen_stock_i_0cff6d_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
